name: Deploy to Digital Ocean

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to DigitalOcean Droplet
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            git clone git@github.com:bobbybaxter/spacetraders.git
            cd spacetraders
            nvm use
            git pull origin main
            echo "${{ secrets.ENV }}" > .env
            npm ci
            npm restart
