name: Deploy to Digital Ocean

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Build env variables
        run: |
          touch .env
          echo "${{ secrets.ENV }}" > .env

      - name: Install dependencies
        run: npm ci

      - name: Restart server application
        run: npm restart
